import type { Metadata } from "next";
import "./globals.css";
import Providers from "./_provider/Provider";
import { Noto_Sans_KR } from "next/font/google";
import { Container } from "@mui/material";
import MuiThemeProvider from "./_provider/ThemeProvider";

const noto = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "RGT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${noto.className} antialiased`}>
        <Providers>
          <MuiThemeProvider>
            <Container maxWidth="lg">{children}</Container>
          </MuiThemeProvider>
        </Providers>
      </body>
    </html>
  );
}
